### ISSUE TITLE
Not show on magento admin panel

### ISSUE THREAD

**Issue by wahyu89** [tobidsn/paymentrandomfee#1]
how to enable this extension on magento admin panel?
i am confusing to find setting this extension.

Thanks

**Comment by tobidsn** [comment]
Change 'ig' in file
https://github.com/tobidsn/paymentrandomfee/blob/master/code/local/Ig/PaymentFee/etc/system.xml#L5

for example 'sales' and check in dashboard->system->configuration->sales

**Comment by arifTulang** [comment]
Not show on magento admin panel has been solved but when i click "payment method fee" menu error 404 show.

Thanks.

**Comment by tobidsn** [comment]
1. Please clear cache, 
2. Delete folder session and cache in directory var
3. Admin logout and login again

**Comment by arifTulang** [comment]
"payment method fee" admin has been solved.
but still error when i click "proceed to checkout" button in frontend.
http://127.0.0.1/magento_1920/index.php/checkout/onepage/
Fatal error: Call to a member function getQuote() on boolean in C:\xampp\htdocs\magento_1920\app\code\core\Mage\Checkout\controllers\OnepageController.php on line 195

Thanks for your help.

![ss6](https://cloud.githubusercontent.com/assets/28687259/26093038/2ee76b54-3a3e-11e7-9d81-edb70753c02e.png)
![ss7](https://cloud.githubusercontent.com/assets/28687259/26093039/2ee8a852-3a3e-11e7-94de-062de2619248.png)
![ss8](https://cloud.githubusercontent.com/assets/28687259/26093040/2ef027bc-3a3e-11e7-932c-ad81be5fb42c.png)
![ss9](https://cloud.githubusercontent.com/assets/28687259/26093041/2ef249e8-3a3e-11e7-9723-4bb37900e385.png)

**Comment by tobidsn** [comment]
Please copy file https://github.com/tobidsn/paymentrandomfee/tree/master/design/frontend/sm_market/default/layout/ig
to your folder frontned template, 
I'am use sm_template

**Comment by arifTulang** [comment]
I'am using magento default template and already copied your file but error still exist. 
this is my var/log/system.log file

I really apreciate your help in resolving my problem.
Thanks.

![ss1](https://cloud.githubusercontent.com/assets/28687259/26145160/9f177d1a-3b15-11e7-8692-8e953d94cbf1.png)
![ss2](https://cloud.githubusercontent.com/assets/28687259/26145139/90c4b1ce-3b15-11e7-8554-fd1c26d19dbf.png)
![ss3](https://cloud.githubusercontent.com/assets/28687259/26145719/adaa6dc2-3b17-11e7-9a28-85ef4db0618d.png)

**Comment by irawanarif** [comment]
is this extension not compatible with onepage checkout?

**Comment by tobidsn** [comment]
@irawanarif Compatible

**Comment by irawanarif** [comment]
@tobidsn i still have the error like @arifTulang on onepage checkout

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by irawanarif** [comment]
Fatal error: Call to a member function getQuote() on boolean in /app/code/core/Mage/Checkout/controllers/OnepageController.php on line 195

**Comment by irawanarif** [comment]
gan @arifTulang boleh disharing solvingnya? :)
